export const PACKAGE_MANAGERS = [
  { value: "AlmaLinux", label: "AlmaLinux" },
  { value: "Alpaquita", label: "Alpaquita" },
  { value: "Alpine", label: "Alpine" },
  { value: "Android", label: "Android" },
  {
    value: "BellSoft Hardened Containers",
    label: "BellSoft Hardened Containers",
  },
  { value: "Bitnami", label: "Bitnami" },
  { value: "Chainguard", label: "Chainguard" },
  { value: "CRAN", label: "CRAN" },
  { value: "crates.io", label: "Crates.io" },
  { value: "Debian", label: "Debian" },
  { value: "Echo", label: "Echo" },
  { value: "GHC", label: "GHC" },
  { value: "GIT", label: "GIT" },
  { value: "GitHub Actions", label: "GitHub Actions" },
  { value: "Go", label: "Go" },
  { value: "Hackage", label: "Hackage" },
  { value: "Hex", label: "Hex" },
  { value: "Julia", label: "Julia" },
  { value: "Linux", label: "Linux" },
  { value: "Mageia", label: "Mageia" },
  { value: "Maven", label: "Maven" },
  { value: "MinimOS", label: "MinimOS" },
  { value: "npm", label: "NPM" },
  { value: "NuGet", label: "NuGet" },
  { value: "openEuler", label: "openEuler" },
  { value: "openSUSE", label: "openSUSE" },
  { value: "OSS-Fuzz", label: "OSS-Fuzz" },
  { value: "Packagist", label: "Packagist" },
  { value: "Pub", label: "Pub" },
  { value: "PyPI", label: "PyPI" },
  { value: "Red Hat", label: "Red Hat" },
  { value: "Rocky Linux", label: "Rocky Linux" },
  { value: "RubyGems", label: "RubyGems" },
  { value: "SUSE", label: "SUSE" },
  { value: "SwiftURL", label: "SwiftURL" },
  { value: "Ubuntu", label: "Ubuntu" },
  { value: "VSCode", label: "VSCode" },
  { value: "Wolfi", label: "Wolfi" },
] as const;

export const ECOSYSTEM_COLORS = [
  "from-red-500 to-orange-500",
  "from-blue-500 to-cyan-500",
  "from-yellow-500 to-orange-500",
  "from-cyan-500 to-blue-500",
  "from-purple-500 to-pink-500",
  "from-red-500 to-pink-500",
  "from-orange-500 to-red-500",
  "from-indigo-500 to-purple-500",
  "from-green-500 to-emerald-500",
  "from-pink-500 to-rose-500",
  "from-violet-500 to-purple-500",
  "from-teal-500 to-cyan-500",
  "from-amber-500 to-yellow-500",
  "from-lime-500 to-green-500",
  "from-sky-500 to-blue-500",
  "from-fuchsia-500 to-pink-500",
  "from-rose-500 to-red-500",
  "from-emerald-500 to-teal-500",
  "from-blue-500 to-indigo-500",
  "from-purple-500 to-violet-500",
  "from-orange-500 to-amber-500",
  "from-cyan-500 to-teal-500",
  "from-pink-500 to-fuchsia-500",
  "from-indigo-500 to-blue-500",
  "from-red-500 to-rose-500",
  "from-green-500 to-lime-500",
  "from-yellow-500 to-amber-500",
  "from-blue-500 to-cyan-500",
  "from-purple-500 to-indigo-500",
  "from-orange-500 to-red-500",
  "from-teal-500 to-cyan-500",
  "from-pink-500 to-rose-500",
  "from-violet-500 to-purple-500",
  "from-emerald-500 to-green-500",
  "from-sky-500 to-blue-500",
  "from-fuchsia-500 to-pink-500",
  "from-rose-500 to-red-500",
  "from-lime-500 to-green-500",
] as const;
