export const PACKAGE_MANAGERS = [
  { value: "AlmaLinux", label: "AlmaLinux" },
  { value: "Alpaquita", label: "Alpaquita" },
  { value: "Alpine", label: "Alpine" },
  { value: "Android", label: "Android" },
  {
    value: "BellSoft Hardened Containers",
    label: "BellSoft Hardened Containers",
  },
  { value: "Bitnami", label: "Bitnami" },
  { value: "Chainguard", label: "Chainguard" },
  { value: "CRAN", label: "CRAN" },
  { value: "crates.io", label: "Crates.io" },
  { value: "Debian", label: "Debian" },
  { value: "Echo", label: "Echo" },
  { value: "GHC", label: "GHC" },
  { value: "GIT", label: "GIT" },
  { value: "GitHub Actions", label: "GitHub Actions" },
  { value: "Go", label: "Go" },
  { value: "Hackage", label: "Hackage" },
  { value: "Hex", label: "Hex" },
  { value: "Julia", label: "Julia" },
  { value: "Linux", label: "Linux" },
  { value: "Mageia", label: "Mageia" },
  { value: "Maven", label: "Maven" },
  { value: "MinimOS", label: "MinimOS" },
  { value: "npm", label: "NPM" },
  { value: "NuGet", label: "NuGet" },
  { value: "openEuler", label: "openEuler" },
  { value: "openSUSE", label: "openSUSE" },
  { value: "OSS-Fuzz", label: "OSS-Fuzz" },
  { value: "Packagist", label: "Packagist" },
  { value: "Pub", label: "Pub" },
  { value: "PyPI", label: "PyPI" },
  { value: "Red Hat", label: "Red Hat" },
  { value: "Rocky Linux", label: "Rocky Linux" },
  { value: "RubyGems", label: "RubyGems" },
  { value: "SUSE", label: "SUSE" },
  { value: "SwiftURL", label: "SwiftURL" },
  { value: "Ubuntu", label: "Ubuntu" },
  { value: "VSCode", label: "VSCode" },
  { value: "Wolfi", label: "Wolfi" },
] as const;
